<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "simpleComponent": {
                        "component": "avto_Sample/js/sample-view-model_3",
                        "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
                    }
                }
            }
        }
    }



</script>
<div class="array-test-ko" data-bind="scope: 'simpleComponent'">
    <button type="button" class="action" data-trigger="trigger">
        <span data-bind="i18n: 'Add item'"></span>
    </button>
    <div class="form-wrap" data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Popup title',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
        <form id="add-item-form" action="" data-bind="submit: addItem">
            <label for="">
                <span data-bind="i18n: 'name'"></span>
                <input type="text" name="productName">
            </label>
            <label for="">
                <span data-bind="i18n: 'qty'"></span>
                <input type="number" name="productQty">
            </label>
            <label for="">
                <span data-bind="i18n: 'price'"></span>
                <input type="number" name="productPrice">
            </label>
            <button type="submit" data-bind="i18n: 'submit'"></button>
        </form>
    </div>
    <h3 data-bind="text: label"></h3>
    <table>
        <tr>
            <th data-bind="i18n: 'name'"></th>
            <th data-bind="i18n: 'reduce'"></th>
            <th data-bind="i18n: 'qty'"></th>
            <th data-bind="i18n: 'increase'"></th>
            <th data-bind="i18n: 'price'"></th>
            <th data-bind="i18n: 'total'"></th>
            <th data-bind="i18n: 'delete'"></th>
        </tr>
        <!-- ko foreach: items -->
        <tr>
            <th data-bind="text: name"></th>
            <th>
                <button data-bind="click: $parent.reduce.bind($parent)">-</button>
            </th>
            <th data-bind="text: qty"></th>
            <th>
                <button data-bind="click: $parent.increase.bind($parent)">+</button>
            </th>
            <th data-bind="text: price"></th>
            <td data-bind="text: $parent.rowTotal($data)"></td>
            <td>
                <button data-bind="click: function(){if($parent.items.length > 0){$parent.items.remove(this)}}" data-bind="i18n: 'delete'">></button>
            </td>
        </tr>
        <!-- /ko -->
    </table>
    <div>
        <p>
            <span>
            <!-- ko i18n:  'Additional charge' --><!-- /ko -->:
                <!-- ko text:  additional_charge($data) --><!-- /ko -->
            </span>
        </p>
        <p>
            <span>
            <!-- ko i18n:  'Total' --><!-- /ko -->:
                <!-- ko text:  total() --><!-- /ko -->
            </span>
        </p>
    </div>
</div>
