<?php
/**
 *avto avtostore Catalog product list addto wishlist template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */

/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<a href="#"
   class="action towishlist"
   title="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
   data-post='<?= /* @noEscape */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
   role="button">
    <span><?= $block->escapeHtml(__('Add to Wishlist')) ?></span>
</a>
