<?php
/**
 *avto avtostore Theme link template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
/**
 * @var $block \Magento\Framework\View\Element\Html\Link
 */
?>
<?php if (!$block->getIsDisabled()) : ?>
    <div class="wishlist-block">
        <a href="<?= $block->escapeUrl($block->getHref()) ?>" class="wishlist-link"
            <?php if ($title = $block->getTitle()) : ?> title="<?= $block->escapeHtmlAttr(__($title)) ?>"<?php endif;?>>
            <?= $block->escapeHtml(__($block->getLabel())) ?>
        </a>
    </div>
<?php endif; ?>
