<?php
/**
 *avto avtostore Layerednavigation layer price-slider template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>

<div class="slider-range-price" data-mage-init='{"myPriceSlider":{}}'>
    <div id="slider-range"></div>
    <a href="http://magento2.local/women/tops-women.html?price=10-20" class="filterHref leftnav-priceblock">
        <span class="minimum-price" id="amount">10</span>
        <span>&nbsp;-&nbsp;</span>
        <span class="maximum-price" id="amount2">700</span>
    </a>
</div>
