<?php
/**
 *avto avtostore Catalog product view custom-tab template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
*/
?>
<div class="custom-tab" id="custom-tab">
    <iframe width="100%" height="560" src="https://www.youtube.com/embed/zKy2I4vSqxw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<?php
//$helper = $this->helper('Magento\Catalog\Helper\Output');
//$product = $block->getProduct();
//$code = $block->getAtCode();
//$className = $block->getCssClass();
//$attributeLabel = $block->getAtLabel();
//$attributeType = $block->getAtType();
//$attributeAddAttribute = $block->getAddAttribute();
//
//if ($attributeLabel && $attributeLabel == 'default') {
//    $attributeLabel = $product->getResource()->getAttribute($code)->getFrontendLabel();
//}
//$attributeValue = $product->getResource()->getAttribute($code)->getFrontend()->getValue($product);
//?>
<!---->
<?php //if ($attributeValue): ?>
<!--    <div class="packaging-content" --><?php // echo $attributeAddAttribute;?><!-->
<!--        --><?php //echo $attributeValue; ?>
<!--    </div>-->
<?php //endif; ?>