<?php
/**
 *avto avtostore Catalog product view custom-tab template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
*/
?>
<div class="custom-tab" id="custom-tab">
    <iframe width="100%" height="560" src="https://www.youtube.com/embed/zKy2I4vSqxw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
