<?php
/**
 *monnier default Theme footer-navigation-child template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<?php
$navigation_title = $block->hasData('footer.navigation.title') && $block->getData('footer.navigation.title');
$navigation_link1 = $block->hasData('footer.navigation.link1') && $block->getData('footer.navigation.link1');
$navigation_link2 = $block->hasData('footer.navigation.link2') && $block->getData('footer.navigation.link2');
$navigation_link3 = $block->hasData('footer.navigation.link3') && $block->getData('footer.navigation.link3');
$navigation_link4 = $block->hasData('footer.navigation.link4') && $block->getData('footer.navigation.link4');
$navigation_link5 = $block->hasData('footer.navigation.link5') && $block->getData('footer.navigation.link5');
$navigation_social_link1 = $block->hasData('footer.navigation.social-link1') && $block->getData('footer.navigation.social-link1');
$navigation_social_link2 = $block->hasData('footer.navigation.social-link2') && $block->getData('footer.navigation.social-link2');
$trusted_shops = $block->hasData('trusted.shops') && $block->getData('trusted.shops');
$trusted_shops_alt = $block->hasData('trusted.shops.alt') && $block->getData('trusted.shops.alt');
?>
<ul class="footer-navigation-column">
    <?php if ($navigation_title) : ?>
        <h5 class="footer-navigation-title"><?= $block->getData('footer.navigation.title')?></h5>
    <?php endif; ?>
    <?php if ($navigation_link1) :?>
        <li><a href="#"><?= $block->getData('footer.navigation.link1')?></a></li>
    <?php endif; ?>
    <?php if ($navigation_link2) :?>
        <li><a href="#"><?= $block->getData('footer.navigation.link2')?></a></li>
    <?php endif; ?>
    <?php if ($navigation_link3) :?>
        <li><a href="#"><?= $block->getData('footer.navigation.link3')?></a></li>
    <?php endif; ?>
    <?php if ($navigation_link4) :?>
        <li><a href="#"><?= $block->getData('footer.navigation.link4')?></a></li>
    <?php endif; ?>
    <?php if ($navigation_link5) :?>
        <li><a href="#"><?= $block->getData('footer.navigation.link5')?></a></li>
    <?php endif; ?>
    <?php if ($trusted_shops) :?>
        <li><a href="#" class="trusted_shops"><img src="<?= $block->getViewFileUrl('images/footer-icons/' . $block->getData('trusted.shops')); ?>" alt="<?= $block->getData('trusted.shops.alt') ?>"></a></li>
    <?php endif; ?>
    <?php if ($navigation_social_link1) :?>
        <li><a href="#" class="facebook_link"><?= $block->getData('footer.navigation.social-link1')?></a></li>
    <?php endif; ?>
    <?php if ($navigation_social_link2) :?>
        <li><a href="#" class="instagram_link"><?= $block->getData('footer.navigation.social-link2')?></a></li>
    <?php endif; ?>
</ul>
