<?php
/**
 *monnier default Theme footer-navigation template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */
?>
<div class="footer-navigation">
    <ul>
        <li><?= $block->getChildHtml('footer.navigation.child1') ?></li>
        <li><?= $block->getChildHtml('footer.navigation.child2') ?></li>
        <li><?= $block->getChildHtml('footer.navigation.child3') ?></li>
        <li><?= $block->getChildHtml('footer.navigation.child4') ?></li>
    </ul>
</div>
